const FileActionTypes = {
    FETCH_FILES: 'FETCH_FILES',
    RECEIVE_FILES: 'RECEIVE_FILES',
    FETCH_FILES_ERROR: 'FETCH_FILES_ERROR',

    FETCH_FILE_DETAILS: 'FETCH_FILE_DETAILS',
    RECEIVE_FILE_DETAILS: 'RECEIVE_FILE_DETAILS',
    FETCH_FILE_DETAILS_ERROR: 'FETCH_FILE_DETAILS_ERROR',
};

export default FileActionTypes;