const FileActionTypes = {
    FETCH_FILES: 'FETCH_FILES',
    RECEIVE_FILES: 'RECEIVE_FILES',
    FETCH_FILES_ERROR: 'FETCH_FILES_ERROR',

    FETCH_FILE_DETAILS: 'FETCH_FILE_DETAILS',
    RECEIVE_FILE_DETAILS: 'RECEIVE_FILE_DETAILS',
    FETCH_FILE_DETAILS_ERROR: 'FETCH_FILE_DETAILS_ERROR',

    DELETE_FILE_REQUEST: 'DELETE_FILE_REQUEST',
    DELETE_FILE_SUCCESS: 'DELETE_FILE_SUCCESS',
    DELETE_FILE_FAIL: 'DELETE_FILE_FAIL'
};

export default FileActionTypes;